### ISSUE TITLE
Remove black bands around image

### ISSUE THREAD

**Issue by kmyn** [FelipeBohnertPaetzold/react-native-gallery#1]
Hi,
I just started testing out this library. It looks pretty neat. Have a small issue though you might be able to help. I'm trying to display the picture only in half of the screen as follows:

![img_7761](https://user-images.githubusercontent.com/18484353/45128250-fd4a4780-b14a-11e8-9dc2-e4a768a6d323.PNG)

The code I'm using is:

```
    render () {
        return (
                <View style={{ flex: 1}}>
                    <View style={{ flex: 1}}>
                        <Gallery images={images} />
                    </View>
                    <View style={{ flex: 1}}>
                        <Text> Hello World!!!! </Text>
                    </View>
                </View>
        );
    }
```

It all works fine. But, when I start zooming the image, I see black bands around it as shown below. How do I remove the black bands and show only the zoomed image?

This issue happens with the basic usage as well. There's a black band around it when the picture is zoomed. For reference, iOS photos app does not seem to have this issue.

![img_7762](https://user-images.githubusercontent.com/18484353/45128296-46020080-b14b-11e8-9d66-7de37ee008a9.PNG)

Thanks :)

**Comment by FelipeBohnertPaetzold** [comment]
Hi @kmyn . I made the addition of the prop imageBackground, you can pass transparent in value. Please update the project. ``npm install react-native-slim-gallery`` or ``yarn add react-native-slim-gallery``


```
    render () {
        return (
                <View style={{ flex: 1}}>
                    <View style={{ flex: 1}}>
                        <Gallery images={images} imageBackground='transparent' />
                    </View>
                    <View style={{ flex: 1}}>
                        <Text> Hello World!!!! </Text>
                    </View>
                </View>
        );
    }
```

**Comment by kmyn** [comment]
Hi @FelipeBohnertPaetzold  thanks for the quick response. I still see the problem. Issue is when I zoom the image and move it around a black background is visible and it stays there when i remove my fingers.

You can compare this view with the photos app on iOS. You see the black background as well but once  you remove the fingers the image fills up the screen.

**Original screen/picture:**

![img_7764](https://user-images.githubusercontent.com/18484353/45132655-badf3580-b15f-11e8-8eb9-9ebb72ef3646.PNG)

**Zoomed picture:**

![img_7765](https://user-images.githubusercontent.com/18484353/45132664-c7fc2480-b15f-11e8-9e7a-b5bab15834b2.PNG)

To make debugging easier, I've used the basic gallery view as follows:

`    render () {
        return (
          <Gallery images={images} imageBackground='#fff' />
        );
    }
`

**Comment by FelipeBohnertPaetzold** [comment]
Excuse me. I said the wrong property, please use in backgroundColor xD
`render () { return ( <Gallery images={images} backgroundColor='#fff' /> ); }
`

**Comment by kmyn** [comment]
Hi @FelipeBohnertPaetzold the problem still happens. I don't think it is an issue with the backgroundColor. 

To reproduce (on iOS) - double click the image and drag down/up the image with a single finger. You will see empty space above/below the image.

**Comment by FelipeBohnertPaetzold** [comment]
@kmyn I understood what you meant. I made an update that corrects this behavior. Please update the package and try again

**Comment by kmyn** [comment]
@FelipeBohnertPaetzold this resolves the problem. Thank youBut, found other issues:

1. Zoom an image; Swipe to the next image; Swipe back to the original image (this image is still in zoomed mode ideally it should be in its original size)
2. Sometimes double click on tap on image does not work. 
3. The transitions are not so smooth.

**Comment by FelipeBohnertPaetzold** [comment]
Tanks, I will see how to solve
